#:kivy 2.0.0

<Appointments@FloatLayout>:
    Label:
        text: "Appointments"
        font_size: 50
        color: 0,0,0,1
        pos_hint: {"x":.42, "y":0.80}
        size_hint: 0.20, 0.20
        height: 100
    
    PicButton:
        source: "ICONS/go_back.png"
        size_hint_y: 0.1
        size_hint_x: 0.1
        pos_hint: {"x": -0.01, "y": 0.005}
        on_press: root.manager.SMMainScreen()